version = 0.1

[default.deploy.parameters]
stack_name = "cognito-pretoken"
resolve_s3 = true
s3_prefix = "cognito-pretoken"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
