apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deploy
  labels: patient-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate #Update, no downtime
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: patient-service
    template:
      metadata:
        labels:
          app: patient-service
      spec:
        containers:
        - name: patient-container
          image: "540522876009.dkr.ecr.ap-southeast-2.amazonaws.com/lms/patient-service" 
          ports:
          - containerPort: 8085
          env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-server-svc:8888"
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value:  "http://eureka-server-svc:8761/eureka/"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 20
        imagePullSecrets:
          - name: ecr-registry-secret