spring:
  application:
    name: patient-service
  profiles:
    active: ${PROFILES_ACTIVE}
  config:
    import: ${CONFIG_SERVER_URL:configserver:http://localhost:8888}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: patient-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      listener:
        test-order:
          testorderCreated: testorder.testorder.created
          tesrorderCompleted: testorder.results.completed
      producer:
        monitoring: patient.monitoring.log


swagger:
  title: "Patient Service"
  version: "1.0"
  description: "PATIENT Endpoints"
  package: "patientservice"
  gateway-url: ${GATEWAY_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

security:
  aes:
    secret-key-base64: ${AES_SECRET_KEY}
  pepper:
    base64: ${PEPPER_BASE64}
