global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iam-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'warehouse-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'test-order-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'instrument-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: 'patient-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'monitoring-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus123'
    static_configs:
      - targets: ['host.docker.internal:8086']

rule_files:
  - alert_rules.yml
